"""
Audio Player for Jarvis.
Plays WAV files generated by Piper.
"""

import simpleaudio as sa
from pathlib import Path


class AudioPlayer:

    def play(self, audio_file: str):

        audio_path = Path(audio_file)

        if not audio_path.exists():
            raise FileNotFoundError(audio_file)

        wave = sa.WaveObject.from_wave_file(str(audio_path))
        play = wave.play()
        play.wait_done()